package com.kmorph.processor.model

enum class ParameterMatchType {
    SAME_CLASS,

    UPCAST_NEEDED_WITH_BOTH_PRIMITIVE,

    DOWNCAST_NEEDED_WITH_BOTH_PRIMITIVE,

    UPCAST_NEEDED_WITH_BOTH_WRAPPER_CLASS,

    DOWNCAST_NEEDED_WITH_BOTH_WRAPPER_CLASS,

    NO_MATCH
}
